version: '3'

services:
  langchain:
    container_name: app
    build:
      context: .
      dockerfile: $PWD/infrastructure/dockerfiles/langchain/Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - superset
    #volumes:
    #  - $PWD/app:/home/app

  superset:
    container_name: superset
    build:
      context: .
      dockerfile: ./infrastructure/dockerfiles/superset/Dockerfile
    ports:
      - "8088:8088"
    restart: always
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
    #volumes:
    #  - $PWD/infrastructure/config/superset/:/home/superset/config/
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"

networks:
  default:
    name: superset-langchain-demo-network
